# Site settings
title:          Megan Verbakel
description:    "Data science notes"
url:            "https://mverbakel.github.io"

# Author
author:
  name:         Megan Verbakel
  email:        megan.verbakel@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       30

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]